Reto.Backend/Controllers/BackendUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using Reto.Class;
using Reto.Helper;
using Reto.Models;
using Reto.Backend.Models;

namespace Reto.Backend.Controllers
{
    public class BackendUserController : BaseController
    {
        #region 建構式
        private IBackendUserRepository _userRepository;

        public IBackendUserRepository userRepo
        {
            get
            {
                return _userRepository;
            }
            set
            {
                _userRepository = value;
            }
        }

        public BackendUserController(IBackendUserRepository userReposiotry)
        {
            _userRepository = userReposiotry;
        }
        #endregion

        [HttpGet]
        [BackendAuthorize]
        public ActionResult Index(BackendUser model, int? page = 1)
        {
            this.List(model, page);
            return View();
        }

        [HttpPost]
        [BackendAuthorize]
        public ActionResult List(BackendUser model, int? page = 1)
        {
            try
            {
                int totalCount = 0;
                Dictionary<string, object> dic = new Dictionary<string, object>();
                if (!string.IsNullOrEmpty(model.Name))
                    dic.Add("Name", model.Name);

                SearchModel search = new SearchModel() 
                                    {
                                        Dic = dic, 
                                        PageIndex = page.HasValue ? page.Value : 1,
                                        PageSize = base.PageSize
                                    };

                var records = userRepo.GetUserList(search, ref totalCount);

                return PartialView("_List", base.PagedList(records, search.PageIndex, totalCount));
            }
            catch(Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        [BackendAuthorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [BackendAuthorize]
        public ActionResult Create(BackendUser model)
        {
            try
            {
                userRepo.Add(ref model);
                return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

Reto.Backend/Views/BackendUser/Index.cshtml
@model IPagedList<Reto.Class.BackendUser>

@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm("List", "BackendUser", new { }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">查詢</h3>
        </div>
        <div class="panel-body">
            <div class="form-group">
                <label for="inputEmail3" class="col-sm-2 control-label">姓名:</label>
                <div class="col-sm-10">
                    @*<input type="email" class="form-control" id="inputEmail3" placeholder="Email">*@
                    @Html.TextBox("Name", null, new { @class = "form-control", @id = "inputEmail3", @placeholder = "請輸入姓名" })
                </div>
            </div>
            <div class="form-group">
                <label for="ddlSex" class="col-sm-2 control-label">姓別:</label>
                <div class="col-sm-10">
                    <select id="Sex" class="form-control">
                        <option value="">請選擇</option>
                        <option value="1">男</option>
                        <option value="0">女</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">是否鎖定:</label>
                <div class="col-sm-10">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox">
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">是否刪除:</label>
                <div class="col-sm-10">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox">
                        </label>
                    </div>
                </div>
            </div>
            @*<div class="form-group">
                    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
                    </div>
                </div>*@
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">查詢</button>
                </div>
            </div>
        </div>
    </div>
}

<div class="row">
    <div class="col-xs-12">
        <div id="grid-table" class="table-responsive">
            @Html.Partial("_List", Model)
        </div>
    </div>
</div>

Reto.Backend/Views/BackendUser/_List.cshtml
@model IPagedList<Reto.Class.BackendUser>

@if (Model != null && Model.Count() > 0)
{
    using (Html.BeginForm("List", "BackendUser", new { }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        <div class="dataTables_wrapper" role="grid">
            <div class="table-header">
                @ViewBag.Result
            </div>
            <table class="table table-striped table-bordered table-hover dataTable">
                <thead>
                    <tr role="row">
                        <th class="center" role="columnheader">帳號</th>
                        <th class="center" role="columnheader">姓名</th>
                        <th class="center" role="columnheader"></th>
                    </tr>
                </thead>
                <tbody role="alert" aria-live="polite" aria-relevant="all">
                    @foreach (var row in Model)
                    {
                        <tr>
                            <td class="center">@Html.ActionLink(row.UserLoginId, "Update")</td>
                            <td class="center">@Html.DisplayFor(m => row.Name)</td>
                            <td class="center"></td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="row">
                <div class="col-sm-4">
                    <div class="dataTables_info">@Model.ItemStart - @Model.ItemEnd 共 @Model.TotalItemCount 筆</div>
                </div>
                <div class="col-sm-8">
                    <div class="dataTables_paginate paging_bootstrap">
                        @Html.Pager(Model.PageSize, Model.PageNumber, Model.TotalItemCount).Options(
                        o => o.Action("List")
                        .DisplayTemplate("_AcePagination")
                        .MaxNrOfPages(10)
                        .AlwaysAddFirstPageNumber())
                    </div>
                </div>
            </div>
        </div>
    }
}
else
{
    <div class="dataTables_wrapper" role="grid">
        <h3 class="text-center">查無資料，請重新查詢！</h3>
    </div>
}